/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_825137_18.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_825137_2[] = { "0", "1" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_825137_17_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
const uint32_t ei_dsp_config_825137_17_axes_size = 10;
ei_dsp_config_raw_t ei_dsp_config_825137_17 = {
    17, // uint32_t blockId
    1, // int implementationVersion
    10, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_825137_17[10] = { 300.26582861871736, 309.86552040328843, 1541.1402116402116, 39.909281293078074, 108.3425925925926, 0.003968253968253968, 0.020282186948853614, 0.010802469135802469, 0.010141093474426807, 0.0028659611992945325 };
const float ei_dn_standard_scaler_scale_825137_17[10] = { 0.42914519077921587, 0.592492186254501, 0.005462753727432724, 0.10041148749807612, 0.015583023242012701, 15.906098958064643, 7.09401507584337, 9.673797031582124, 9.980928846607348, 18.706307789663377 };
const float ei_dn_standard_scaler_var_825137_17[10] = { 5.429895856795012, 2.8486214845455486, 33510.17963522858, 99.18207693577709, 4118.096916029785, 0.003952506928697404, 0.01987081984142574, 0.010685775796372381, 0.01003825169756968, 0.0028577474656986466 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_825137_17 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_825137_17,
    .mean_data_len = 10,
    .scale_data = (float *)ei_dn_standard_scaler_scale_825137_17,
    .scale_data_len = 10,
    .var_data = (float *)ei_dn_standard_scaler_var_825137_17,
    .var_data_len = 10
};
ei_data_normalization_t ei_data_normalization_config_825137_17 = {
    (void *) &ei_data_normalization_standard_scaler_config_825137_17, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_825137_2_size = 1;
ei_model_dsp_t ei_dsp_blocks_825137_2[ei_dsp_blocks_825137_2_size] = {
    { // DSP block 17
        17,
        10, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_825137_17, // pointer to config struct
        ei_dsp_config_825137_17_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_825137_17_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_825137_17, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_825137_18 = {
    .implementation_version = 1,
    .model = tflite_learn_825137_18,
    .model_size = tflite_learn_825137_18_len,
    .arena_size = tflite_learn_825137_18_arena_size
};

const uint8_t ei_output_tensors_indices_825137_18[1] = { 0 };
const uint8_t ei_output_tensors_size_825137_18 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_825137_18 = {
    .implementation_version = 1,
    .block_id = 18,
    .output_tensors_indices = ei_output_tensors_indices_825137_18,
    .output_tensors_size = ei_output_tensors_size_825137_18,
    .quantized = 1,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_825137_18,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_825137_2_size = 1;
const uint32_t ei_learning_block_825137_18_inputs[1] = { 17 };
const uint8_t ei_learning_block_825137_18_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_825137_2[ei_learning_blocks_825137_2_size] = {
    {
        18,
        &run_nn_inference,
        (void*)&ei_learning_block_config_825137_18,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_825137_18_inputs,
        ei_learning_block_825137_18_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_825137_18 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_825137_2_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_825137_2[ei_postprocessing_blocks_825137_2_size] = {
    {
        .block_id = 18,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_825137_18,
        .input_block_id = 18
    },
};

const uint8_t freeform_outputs_825137_2_size = 0;

uint32_t *freeform_outputs_825137_2 = nullptr;

const ei_impulse_t impulse_825137_2 = {
    .project_id = 825137,
    .project_owner = "Eslam_32",
    .project_name = "Green Box Predictive Maintenance",
    .impulse_id = 2,
    .impulse_name = "Impulse #2",
    .deploy_version = 1,

    .nn_input_frame_size = 10,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 10,
    .dsp_input_frame_size = 1 * 10,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1000,
    .frequency = 1,

    .dsp_blocks_size = ei_dsp_blocks_825137_2_size,
    .dsp_blocks = ei_dsp_blocks_825137_2,

    .learning_blocks_size = ei_learning_blocks_825137_2_size,
    .learning_blocks = ei_learning_blocks_825137_2,

    .postprocessing_blocks_size = ei_postprocessing_blocks_825137_2_size,
    .postprocessing_blocks = ei_postprocessing_blocks_825137_2,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "Air temperature [K] + Process temperature [K] + Rotational speed [rpm] + Torque [Nm] + Tool wear [min] + TWF + HDF + PWF + OSF + RNF",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_825137_2,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_825137_2_size,
    .freeform_outputs = freeform_outputs_825137_2
};

ei_impulse_handle_t impulse_handle_825137_2 = ei_impulse_handle_t( &impulse_825137_2 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_825137_2;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_825137_2;
const auto ei_dsp_blocks_size = ei_dsp_blocks_825137_2_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_825137_2;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
